# https://github.com/release-it/release-it/blob/master/config/release-it.json

hooks: {}

# https://github.com/release-it/release-it/blob/master/docs/git.md
git:
  addUntrackedFiles: false
  commit: false
  push: true
  # requireBranch: 'release/stable'
  requireCommits: true
  requireCleanWorkingDir: true
  requireUpstream: true
  tag: true
  tagArgs: [ '--force' ]
  tagAnnotation: |
    build ${version}:
    ${changelog}
  tagName: 'v${version}'

#https://github.com/release-it/release-it/blob/master/docs/npm.md
npm:
  ignoreVersion: true
  publish: false

# https://github.com/release-it/release-it/blob/master/docs/github-releases.md
github:
  draft: false
  release: false
