/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */

export const portal_schema_V1 = {
    entities: {
        dataSourceProperties: {
            api: "api",
            data: "data",
            version: "v9.2",
            schema: "portalschemav1",
            singleEntityURL:
                "{dataverseOrgUrl}/{api}/{data}/{version}/{entity}({entityId})",
            multiEntityURL: "{dataverseOrgUrl}/{api}/{data}/{version}/{entity}",
        },
        entity: [
            {
                relationships: "",
                _vscodeentityname: "websites",
                _dataverseenityname: "adx_websites",
                _displayname: "Website",
                _etc: "10026",
                _primaryidfield: "adx_websiteid",
                _primarynamefield: "adx_name",
                _disableplugins: "true",
                _foldername: "",
                _propextension: "website",
                _exporttype: "SingleFolder",
                _fetchQueryParameters:
                    "?$select=adx_name,adx_websiteid,adx_website_language",
            },
            {
                _vscodeentityname: "websitelanguages",
                _dataverseenityname: "adx_websitelanguages",
                _displayname: "Website Language",
                _etc: "10046",
                _primaryidfield: "adx_websitelanguageid",
                _primarynamefield: "adx_name",
                _disableplugins: "true",
                _foldername: "",
                _propextension: "websitelanguage",
                _exporttype: "SingleFile",
                _fetchQueryParameters:
                    "?$select=adx_websitelanguageid,_adx_portallanguageid_value",
            },
            {
                _vscodeentityname: "portallanguages",
                _dataverseenityname: "adx_portallanguages",
                _displayname: "Portal Language",
                _etc: "10032",
                _primaryidfield: "adx_portallanguageid",
                _primarynamefield: "adx_name",
                _disableplugins: "true",
                _downloadThroughChild: "true",
                _foldername: "",
                _propextension: "portallanguage",
                _exporttype: "SingleFile",
                _fetchQueryParameters: "?$select=adx_lcid,adx_languagecode",
            },
            {
                relationships: "",
                _vscodeentityname: "webpages",
                _dataverseenityname: "adx_webpages",
                _displayname: "Web Page",
                _etc: "10024",
                _primaryidfield: "adx_webpageid",
                _primarynamefield: "adx_name",
                _disableplugins: "true",
                _foldername: "web-pages",
                _propextension: "webpage",
                _exporttype: "SubFolders",
                _languagefield: "_adx_webpagelanguageid_value",
                _languagegroupby: "adx_rootwebpageid",
                _fetchQueryParameters:
                    "?$filter=adx_webpageid%20eq%20{entityId}&$select=adx_name,adx_copy,adx_customcss,adx_customjavascript,adx_partialurl,_adx_webpagelanguageid_value",
                _multiFileFetchQueryParameters:
                    "?$filter=_adx_websiteid_value%20eq%20{websiteId}&$select=adx_webpageid,_adx_webpagelanguageid_value,adx_name,adx_copy,adx_customcss,adx_customjavascript,adx_partialurl",
                _attributes: "adx_customcss,adx_customjavascript,adx_copy",
                _attributesExtension: new Map([
                    ["adx_customcss", "customcss.css"],
                    ["adx_customjavascript", "customjs.js"],
                    ["adx_copy", "webpage.copy.html"],
                ]),
            },
            {
                relationships: "",
                _vscodeentityname: "webfiles",
                _dataverseenityname: "annotations",
                _displayname: "Web File",
                _etc: "10020",
                _primaryidfield: "_objectid_value",
                _primarynamefield: "filename",
                _disableplugins: "true",
                _foldername: "web-files",
                _propextension: "webfile",
                _exporttype: "SingleFolder",
                _fetchQueryParameters:
                    "?$filter=_objectid_value%20eq%20{entityId}%20&$select=mimetype,documentbody,filename,annotationid,_objectid_value",
                _multiFileFetchQueryParameters: "",
                _attributes: "documentbody",
                _attributesExtension: new Map([["documentbody", "css"]]),
                _mappingEntityId: "annotationid", // Webfile in old schema are maintained with two dataverse entity adx_webfile and annotations. This Id acts as foreign key for that mapping
            },
            {
                relationships: "",
                _vscodeentityname: "contentsnippet",
                _dataverseenityname: "adx_contentsnippets",
                _displayname: "Content Snippet",
                _etc: "10016",
                _primaryidfield: "adx_contentsnippetid",
                _primarynamefield: "adx_name",
                _disableplugins: "true",
                _foldername: "content-snippets",
                _propextension: "contentsnippet",
                _exporttype: "SingleFolder",
                _languagefield: "_adx_contentsnippetlanguageid_value",
                _languagegroupby: "adx_name",
                _fetchQueryParameters:
                    "?$filter=adx_contentsnippetid%20eq%20{entityId}&$select=adx_name,adx_value,_adx_contentsnippetlanguageid_value,_adx_contentsnippetlanguageid_value",
                _multiFileFetchQueryParameters:
                    "?$filter=_adx_websiteid_value%20eq%20{websiteId}&$select=adx_name,adx_value,_adx_contentsnippetlanguageid_value,_adx_contentsnippetlanguageid_value",
                _attributes: "adx_value",
                _attributesExtension: new Map([["adx_value", "html"]]),
            },
            {
                relationships: "",
                _vscodeentityname: "webtemplates",
                _dataverseenityname: "adx_webtemplates",
                _displayname: "Web Template",
                _etc: "10060",
                _primaryidfield: "adx_webtemplateid",
                _primarynamefield: "adx_name",
                _disableplugins: "true",
                _foldername: "web-templates",
                _propextension: "webtemplate",
                _exporttype: "SingleFolder",
                _fetchQueryParameters:
                    "?$filter=adx_webtemplateid%20eq%20{entityId}&$select=adx_name,adx_source",
                _multiFileFetchQueryParameters:
                    "?$filter=_adx_websiteid_value%20eq%20{websiteId}&$select=adx_name,adx_source",
                _attributes: "adx_source",
                _attributesExtension: new Map([["adx_source", "html"]]),
            },
            {
                relationships: "",
                _vscodeentityname: "lists",
                _dataverseenityname: "adx_entitylists",
                _displayname: "Lists",
                _etc: "10060",
                _primaryidfield: "",
                _primarynamefield: "",
                _disableplugins: "true",
                _foldername: "lists",
                _propextension: "",
                _exporttype: "SingleFolder",
                _fetchQueryParameters: "",
                _multiFileFetchQueryParameters: "",
                _attributes: "",
                _attributesExtension: new Map([["", ""]]),
            },
            {
                relationships: "",
                _vscodeentityname: "basicforms",
                _dataverseenityname: "adx_entityforms",
                _displayname: "Basic Forms",
                _etc: "10060",
                _primaryidfield: "",
                _primarynamefield: "",
                _disableplugins: "true",
                _foldername: "basic-forms",
                _propextension: "",
                _exporttype: "SingleFolder",
                _fetchQueryParameters: "",
                _multiFileFetchQueryParameters: "",
                _attributes: "",
                _attributesExtension: new Map([["", ""]]),
            },
            {
                relationships: "",
                _vscodeentityname: "advancedforms",
                _dataverseenityname: "adx_webforms",
                _displayname: "Advanced Forms",
                _etc: "10060",
                _primaryidfield: "",
                _primarynamefield: "",
                _disableplugins: "true",
                _foldername: "advanced-forms",
                _propextension: "",
                _exporttype: "SubFolders",
                _fetchQueryParameters: "",
                _multiFileFetchQueryParameters: "",
                _attributes: "",
                _attributesExtension: new Map([["", ""]]),
            },
        ],
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
};

export const portal_schema_V2 = {
    entities: {
        dataSourceProperties: {
            api: "api",
            data: "data",
            version: "v9.2",
            schema: "portalschemav2",
            singleEntityURL:
                "{dataverseOrgUrl}/{api}/{data}/{version}/{entity}({entityId})",
            multiEntityURL: "{dataverseOrgUrl}/{api}/{data}/{version}/{entity}",
        },
        entity: [
            {
                relationships: "",
                _vscodeentityname: "websites",
                _dataverseenityname: "powerpagesites",
                _displayname: "Website",
                _etc: "10026",
                _primaryidfield: "powerpagesiteid",
                _primarynamefield: "name",
                _disableplugins: "true",
                _foldername: "",
                _propextension: "website",
                _exporttype: "SingleFolder",
                _fetchQueryParameters: "?$select=name,powerpagesiteid,content",
            },
            {
                relationships: "",
                _vscodeentityname: "websitelanguages",
                _dataverseenityname: "powerpagesitelanguages",
                _displayname: "Power Page Site Language",
                _foldername: "",
                _etc: "10273",
                _primaryidfield: "powerpagesitelanguageid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _fetchQueryParameters:
                    "?$select=powerpagesitelanguageid,languagecode,lcid",
            },
            {
                relationships: "",
                _vscodeentityname: "portallanguages",
                _dataverseenityname: "powerpagesitelanguages",
                _displayname: "Power Page Site Language",
                _foldername: "",
                _etc: "10273",
                _primaryidfield: "powerpagesitelanguageid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _fetchQueryParameters:
                    "?$select=powerpagesitelanguageid,languagecode,lcid",
            },
            {
                relationships: "",
                _vscodeentityname: "webpages",
                _dataverseenityname: "powerpagecomponents",
                _displayname: "Web Page",
                _etc: "10271",
                _primaryidfield: "powerpagecomponentid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _exporttype: "SubFolders",
                _languagefield: "powerpagesitelanguageid",
                _foldername: "web-pages",
                _fetchQueryParameters:
                    "?$filter=powerpagecomponentid%20eq%20{entityId}&$select=name,content,powerpagesitelanguageid",
                _multiFileFetchQueryParameters:
                    "?$filter=_powerpagesiteid_value%20eq%20{websiteId}%20and%20powerpagecomponenttype%20eq%202%20and%20_powerpagesitelanguageid_value%20ne%20null&$select=name,content,_powerpagesitelanguageid_value",
                _attributes:
                    "content.customcss,content.customjavascript,content.copy",
                _attributesExtension: new Map([
                    ["content.customcss", "customcss.css"],
                    ["content.customjavascript", "customjs.js"],
                    ["content.copy", "webpage.copy.html"],
                ]),
            },
            {
                relationships: "",
                _vscodeentityname: "webfiles",
                _dataverseenityname: "powerpagecomponents",
                _displayname: "Web File",
                _etc: "10271",
                _primaryidfield: "powerpagecomponentid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _exporttype: "SingleFolder",
                _foldername: "web-files",
                _fetchQueryParameters:
                    "?$filter=powerpagecomponentid%20eq%20{entityId}&$select=name",
                _multiFileFetchQueryParameters:
                    "?$filter=_powerpagesiteid_value%20eq%20{websiteId}%20and%20powerpagecomponenttype%20eq%203&$select=name,content,_powerpagesitelanguageid_value",
                _attributes: "filecontent",
                _attributesExtension: new Map([["filecontent", "css"]]),
                _mappingAttributeFetchQuery: new Map([
                    ["filecontent", "({entityId})/filecontent"],
                ]),
            },
            {
                relationships: "",
                _vscodeentityname: "contentsnippet",
                _dataverseenityname: "powerpagecomponents",
                _displayname: "Content Snippet",
                _etc: "10271",
                _primaryidfield: "powerpagecomponentid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _exporttype: "SingleFolder",
                _foldername: "content-snippets",
                _fetchQueryParameters:
                    "?$filter=powerpagecomponentid%20eq%20{entityId}&$select=name,content",
                _multiFileFetchQueryParameters:
                    "?$filter=_powerpagesiteid_value%20eq%20{websiteId}%20and%20powerpagecomponenttype%20eq%207%20and%20_powerpagesitelanguageid_value%20ne%20null&$select=name,content,_powerpagesitelanguageid_value",
                _attributes: "content.value",
                _attributesExtension: new Map([["content.value", "html"]]),
            },
            {
                relationships: "",
                _vscodeentityname: "webtemplates",
                _dataverseenityname: "powerpagecomponents",
                _displayname: "Web Template",
                _etc: "10271",
                _primaryidfield: "powerpagecomponentid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _exporttype: "SingleFolder",
                _foldername: "web-templates",
                _fetchQueryParameters:
                    "?$filter=powerpagecomponentid%20eq%20{entityId}&$select=name,content",
                _multiFileFetchQueryParameters:
                    "?$filter=_powerpagesiteid_value%20eq%20{websiteId}%20and%20powerpagecomponenttype%20eq%208&$select=name,content,_powerpagesitelanguageid_value",
                _attributes: "content.source",
                _attributesExtension: new Map([["content.source", "html"]]),
            },
            {
                relationships: "",
                _vscodeentityname: "lists",
                _dataverseenityname: "powerpagecomponents",
                _displayname: "Lists",
                _etc: "10271",
                _primaryidfield: "powerpagecomponentid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _exporttype: "SingleFolder",
                _foldername: "lists",
                _fetchQueryParameters:
                    "?$filter=powerpagecomponentid%20eq%20{entityId}&$select=name,content",
                _multiFileFetchQueryParameters:
                    "?$filter=_powerpagesiteid_value%20eq%20{websiteId}%20and%20powerpagecomponenttype%20eq%2017%20and%20_powerpagesitelanguageid_value%20ne%20null&$select=name,content,_powerpagesitelanguageid_value",
                _attributes: "content.source",
                _attributesExtension: new Map([["", ""]]),
            },
            {
                relationships: "",
                _vscodeentityname: "basicforms",
                _dataverseenityname: "powerpagecomponents",
                _displayname: "Basic Forms",
                _etc: "10271",
                _primaryidfield: "powerpagecomponentid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _exporttype: "SingleFolder",
                _foldername: "basic-forms",
                _fetchQueryParameters:
                    "?$filter=powerpagecomponentid%20eq%20{entityId}&$select=name,content",
                _multiFileFetchQueryParameters:
                    "?$filter=_powerpagesiteid_value%20eq%20{websiteId}%20and%20powerpagecomponenttype%20eq%2015%20and%20_powerpagesitelanguageid_value%20ne%20null&$select=name,content,_powerpagesitelanguageid_value",
                _attributes: "content.source",
                _attributesExtension: new Map([["", ""]]),
            },
            {
                relationships: "",
                _vscodeentityname: "advancedforms",
                _dataverseenityname: "powerpagecomponents",
                _displayname: "Advanced Forms",
                _etc: "10271",
                _primaryidfield: "powerpagecomponentid",
                _primarynamefield: "name",
                _disableplugins: "false",
                _exporttype: "SubFolders",
                _foldername: "advanced-forms",
                _fetchQueryParameters:
                    "?$filter=powerpagecomponentid%20eq%20{entityId}&$select=name,content",
                _multiFileFetchQueryParameters:
                    "?$filter=_powerpagesiteid_value%20eq%20{websiteId}%20and%20powerpagecomponenttype%20eq%2019%20and%20_powerpagesitelanguageid_value%20ne%20null&$select=name,content,_powerpagesitelanguageid_value",
                _attributes: "content.source",
                _attributesExtension: new Map([["", ""]]),
            },
        ],
    },
};
