/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */

export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_INVOKED = 'VSCodeExtensionGitHubPowerPagesAgentInvoked';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_ORG_DETAILS = 'VSCodeExtensionGitHubPowerPagesAgentOrgDetails';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_ORG_DETAILS_NOT_FOUND = 'VSCodeExtensionGitHubPowerPagesAgentOrgDetailsNotFound';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_SCENARIO = 'VSCodeExtensionGitHubPowerPagesAgentScenario';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_SCENARIO_FEEDBACK_THUMBSUP = 'VSCodeExtensionGitHubPowerPagesAgentScenarioFeedbackThumbsUp';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_SCENARIO_FEEDBACK_THUMBSDOWN = 'VSCodeExtensionGitHubPowerPagesAgentScenarioFeedbackThumbsDown';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_ERROR = 'VSCodeExtensionGitHubPowerPagesAgentError';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_WEBPAGE_RELATED_FILES = 'VSCodeExtensionGitHubPowerPagesAgentWebpageRelatedFiles';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_LOCATION_REFERENCED = 'VSCodeExtensionGitHubPowerPagesAgentLocationReferenced';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_NO_PROMPT = 'VSCodeExtensionGitHubPowerPagesAgentNoPrompt';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_WELCOME_PROMPT = 'VSCodeExtensionGitHubPowerPagesAgentWelcomePrompt';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_SUCCESSFUL_PROMPT = 'VSCodeExtensionGitHubPowerPagesAgentSuccessfulPrompt';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_NOT_AVAILABLE_ECS = 'VSCodeExtensionGitHubPowerPagesAgentNotAvailableECS';
export const VSCODE_EXTENSION_NL2PAGE_REQUEST_FAILED = 'VSCodeExtensionNL2PageRequestFailed';
export const VSCODE_EXTENSION_NL2PAGE_REQUEST_SUCCESS = 'VSCodeExtensionNL2PageRequestSuccess';
export const VSCODE_EXTENSION_NL2SITE_REQUEST_FAILED = 'VSCodeExtensionNL2SiteRequestFailed';
export const VSCODE_EXTENSION_NL2SITE_REQUEST_SUCCESS = 'VSCodeExtensionNL2SiteRequestSuccess';
export const VSCODE_EXTENSION_CREATE_SITE_REQUEST_SUCCESS = 'VSCodeExtensionNL2SiteRequestSuccess';
export const VSCODE_EXTENSION_CREATE_SITE_COMMAND_FAILED = 'VSCodeExtensionNL2SiteCommandFailed';
export const VSCODE_EXTENSION_GITHUB_POWER_PAGES_AGENT_COMMAND_TRIGGERED = 'VSCodeExtensionGitHubPowerPagesAgentCommandTriggered';
export const VSCODE_EXTENSION_NL2PAGE_REQUEST = 'VSCodeExtensionNL2PageRequest';
export const VSCODE_EXTENSION_NL2SITE_REQUEST = 'VSCodeExtensionNL2SiteRequest';
export const VSCODE_EXTENSION_PREVIEW_SITE_PAGES = 'VSCodeExtensionPreviewSitePages';
export const VSCODE_EXTENSION_PREVIEW_SITE_PAGES_ERROR = 'VSCodeExtensionPreviewSitePagesError';
export const VSCODE_EXTENSION_POPULATE_SITE_RECORDS_START = 'VSCodeExtensionPopulateSiteRecordsStart';
export const VSCODE_EXTENSION_POPULATE_SITE_RECORDS_SUCCESS = 'VSCodeExtensionPopulateSiteRecordsSuccess';
export const VSCODE_EXTENSION_POPULATE_SITE_RECORDS_ERROR = 'VSCodeExtensionPopulateSiteRecordsError';
export const VSCODE_EXTENSION_CREATE_SITE_SAVE_OPERATION_ERROR = 'VSCodeExtensionCreateSiteSaveOperationError';
export const VSCODE_EXTENSION_CREATE_SITE_OPERATION_ERROR = 'VSCodeExtensionCreateSiteOperationError';
export const VSCODE_EXTENSION_CREATE_SITE_OPERATION_SUCCESS = 'VSCodeExtensionCreateSiteOperationSuccess';
export const VSCODE_EXTENSION_CREATE_SITE_COMPONENT_OPERATION_ERROR = 'VSCodeExtensionCreateSiteComponentOperationError';
export const VSCODE_EXTENSION_CREATE_SITE_COMPONENT_OPERATION_SUCCESS = 'VSCodeExtensionCreateSiteComponentOperationSuccess';
export const VSCODE_EXTENSION_CREATE_SITE_COMPONENT_PROCESSING_ERROR = 'VSCodeExtensionCreateSiteComponentProcessingError';
export const VSCODE_EXTENSION_CREATE_SITE__FILE_COMPONENT_OPERATION_ERROR = 'VSCodeExtensionCreateSiteFileComponentOperationError';
export const VSCODE_EXTENSION_CREATE_SITE__FILE_COMPONENT_OPERATION_SUCCESS = 'VSCodeExtensionCreateSiteFileComponentOperationSuccess';
export const VSCODE_EXTENSION_CREATE_SITE__FILE_COMPONENT_PROCESSING_ERROR = 'VSCodeExtensionCreateSiteFileComponentProcessingError';
export const VSCODE_EXTENSION_CREATE_SITE_PROVISIONING_COMPLETED = 'VSCodeExtensionCreateSiteProvisioningCompleted';
export const VSCODE_EXTENSION_CREATE_SITE_PROVISIONING_FAILED = 'VSCodeExtensionCreateSiteProvisioningFailed';
export const VSCODE_EXTENSION_CREATE_SITE_PROVISIONING_UNKNOWN_STATUS = 'VSCodeExtensionCreateSiteProvisioningUnknownStatus';
export const VSCODE_EXTENSION_CREATE_SITE_PROVISIONING_TIMEOUT = 'VSCodeExtensionCreateSiteProvisioningTimeout';

