name: Localization Update

on:
  pull_request:
    branches:
      - main
    paths:
      - 'loc/translations-import/**'
  workflow_dispatch:  # Add this for manual testing

jobs:
  update-localization:
    name: Update Localization Files
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.LOC_UPDATE_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Translations Import
        run: npm run translations-import

      - name: Add Changes
        run: git add -A
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.LOC_UPDATE_PAT }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Automated localization update from CI" -a
          git push
